### ISSUE TITLE
get from a github repository

### ISSUE THREAD

**Issue by nju33** [nju33/moza#3]
## Configure

```bash
moza configure # inspired by awscli
github access token: ***
github username: ***
github repository: ***
```

then, to create `~/.moza/config` following like

```toml
[default]
github_access_token = ***
github_username = ***
github_repository = ***
```

## Generate|Copy?

```bash
moza gen tsconfig.json           # make in same name `tsconfig.json` in local 
moza gen tsconfig.build.json  # as above
```
